language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - os
    
script:
    - mkdir build
    - cd build
    - ctest --output-on-failure
    - qmake -project
    - qmake trpo.pro 
    - make
