language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - os
    
script:
    - cd build
    - qmake -project "CONFIG += qtestlib"
    - qmake
    - make
    - make test
    - ./bin/tests
    - ctest --output-on-failure
